- build.gradle
- control/src/main/java/com/postco/control/service/TestConsumer.java
- core/build.gradle
- core/src/main/java/com/postco/core/config/KafkaConfig.java
- docker-compose.yml
- kafka-monitoring.yml
- kafka-ui.yml
- operation/src/main/java/com/postco/operation/presentation/ApiTestController.java
- operation/src/main/java/com/postco/operation/service/TestProducer.java
- prometheus.yml
> Feat: 카프카 설정 완료

- cache-service/build.gradle
- cache-service/src/main/java/com/postco/cacheservice/config/RedisConfig.java
- cache-service/src/main/java/com/postco/cacheservice/kafka/RedisKafkaConsumer.java
- cache-service/src/main/java/com/postco/cacheservice/service/MaterialDataService.java
- cache-service/src/test/java/com/postco/cacheservice/config/RedisTemplateTest.java
- cache-service/src/test/java/com/postco/cacheservice/kafka/RedisKafkaConsumerTest.java
- cache-service/src/test/java/com/postco/cacheservice/service/MaterialDataServiceTest.java
- control/src/main/java/com/postco/control/ControlApp.java
- control/src/main/java/com/postco/control/service/RedisService.java
- control/src/main/java/com/postco/control/service/impl/RedisServiceImpl.java
- core/build.gradle
- core/src/main/java/com/postco/core/common/redis/RedisDataService.java
- core/src/main/java/com/postco/core/config/RedisConfig.java
- operation/src/main/java/com/postco/operation/presentation/dto/MaterialsDTO.java
- operation/src/main/java/com/postco/operation/service/KafkaMessageService.java
- operation/src/main/java/com/postco/operation/service/RedisService.java
- operation/src/main/java/com/postco/operation/service/impl/KafkaMessageServiceImpl.java
- 14
- feat/reactiveRedis/yerimee
- 데이터 저장방식 hash 로 변경
- reactiveRedis 설정으로 변경
- 중앙 모듈에서 조회하는 서비스 메서드 추가 
- 
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> 재료 데이터 Hash 저장 및 Core 에 재료 조회 서비스 구현

- control/src/main/java/com/postco/control/presentation/ControlController.java
- control/src/main/java/com/postco/control/presentation/dto/response/TargetMaterialDTO.java
- control/src/main/java/com/postco/control/service/ControlService.java
- 예시 : 17
- feat/bc001a-table/leeyc
- 작업대상재 관리 화면(표) - 품종 별 차공정 현황을 보여주는 로직 작성
- Table을 위한 DTO 추가 
- #17 
- 우선 데이터가 없어서 임의로 만들어서 사용(데이터 및 DTO) 하고, 코드에 두었는데!이 부분 지우고 병합하는게 나을것 같다면 이야기 해주세요! 수정하도록 하겠습니다 :)
- API URL: http://localhost:8086/control/fc001a/table 
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @dudco0040 
- @yerimee82
> Feat: 작업대상재(표) 1차 구현

- control/src/main/java/com/postco/control/ControlApp.java
- control/src/main/java/com/postco/control/domain/TargetMaterial.java
- control/src/main/java/com/postco/control/domain/repository/TargetMaterialRepository.java
- control/src/main/java/com/postco/control/presentation/ControlController.java
- control/src/main/java/com/postco/control/presentation/dto/response/MaterialDTO.java
- control/src/main/java/com/postco/control/presentation/dto/response/TargetMaterialDTO.java
- control/src/main/java/com/postco/control/service/ControlService.java
- control/src/main/java/com/postco/control/service/impl/RedisServiceImpl.java
- 25
- feat/bc001a-list/leeyc
- 공정 별 작업 대상재 추출 기능 구현
- 작업대상재 추출 로직 수정
- 작업대상재 조회 시, 공정 별 조회할 수 있도록 기능 추가
- #25 
- 
- API 테스트 및 프론트 연결로 확인 완료하였습니다~
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @dudco0040 
- @yerimee82
> Feat/bc001a list/leeyc

- control/src/main/java/com/postco/control/ControlApp.java
- control/src/main/java/com/postco/control/domain/repository/ExtractionCriteriaDetailRepository.java
- control/src/main/java/com/postco/control/domain/repository/ExtractionCriteriaRepository.java
- control/src/main/java/com/postco/control/presentation/ControlController.java
- control/src/main/java/com/postco/control/presentation/dto/response/CriteriaDetailDTO.java
- control/src/main/java/com/postco/control/presentation/dto/response/ExtractionStandardDTO.java
- control/src/main/java/com/postco/control/service/ControlService.java
- control/src/main/java/com/postco/control/service/impl/CriteriaServiceImpl.java
- control/src/main/java/com/postco/control/service/impl/RedisServiceImpl.java
- control/src/test/java/com/postco/control/service/CriteriaServiceTest.java
- #22 
- feat/bmc001/pinky
- 추출기준 관리에서 API를 통해 기준을 조회하고 등록가능
- 
-
- 영채꺼랑 합치다보니 충돌이 일어날수도.... 에러기준은 파일 따로 만들겠슴돠
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> feat/bmc001/pinky   Feat: 추출기준 get 및 post 완료

- control/src/main/java/com/postco/control/domain/repository/ErrorCriteriaDetailRepository.java
- control/src/main/java/com/postco/control/presentation/ControlController.java
- control/src/main/java/com/postco/control/presentation/dto/response/ErrorStandardDTO.java
- control/src/main/java/com/postco/control/service/ErrorManagementService.java
- control/src/main/java/com/postco/control/service/ManagementService.java
- #31 
- feat/bme001/pinky
- 에러기준관련 API 만들었습니다
- 에러기준이 2CAL 까지 밖에 없어서 데이터를 더 만들지, 프론트에서 없는 기준은 버릴지 고려해봐야할 것 같습니다
- #22 영채랑 계속 파일 겹쳐서 Management Service를 따로 만들었습니다
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> feat/bme001/pinky 에러기준 API 구현완료

- control/src/main/java/com/postco/control/domain/TargetMaterial.java
- control/src/main/java/com/postco/control/domain/repository/TargetMaterialRepository.java
- control/src/main/java/com/postco/control/service/TargetMaterialService.java
- control/src/main/java/com/postco/control/service/impl/TargetMaterialServiceImpl.java
- core/src/main/java/com/postco/core/utils/mapper/TargetMaterialMapper.java
- #45 
- feat/connect/yerimee
- 에러 수정 및 머지 후 스케쥴과 합치기 진행 예정
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Fix : 추출 에러 수정

- control/src/main/java/com/postco/control/ControlApp.java
- control/src/main/java/com/postco/control/presentation/TargetMaterialController.java
- control/src/main/java/com/postco/control/presentation/dto/TargetViewDTO.java
- control/src/main/java/com/postco/control/service/TargetMaterialQueryService.java
- control/src/main/java/com/postco/control/service/impl/TargetMaterialQueryServiceImpl.java
- control/src/main/java/com/postco/control/service/impl/redis/ControlRedisQueryService.java
- operation/src/main/java/com/postco/operation/domain/entity/Order.java
- #52 
- feat/control-fix/yerimee
- 레디스 받아오는 부분 수정 및 프론트용 dto 에 매핑함. 
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Feat: 작업대상재 조회 controller 구현

- control/src/main/java/com/postco/control/domain/repository/TargetMaterialRepository.java
- control/src/main/java/com/postco/control/presentation/TargetMaterialController.java
- control/src/main/java/com/postco/control/service/TargetMaterialQueryService.java
- control/src/main/java/com/postco/control/service/impl/TargetMaterialQueryServiceImpl.java
- control/src/main/java/com/postco/control/service/impl/redis/ControlRedisQueryService.java
- core/src/main/java/com/postco/core/dto/SCHMaterialDTO.java
- core/src/main/java/com/postco/core/dto/ScheduleResultDTO.java
- 급한 거 먼저 해결했읍니다. 공정별 조회 
- feat/work-instruction-yerimee
- 
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Feat: 작업대상재 공정별 조회

- control/src/main/java/com/postco/control/presentation/ErrorMaterialController.java
- control/src/main/java/com/postco/control/presentation/TargetMaterialController.java
- control/src/main/java/com/postco/control/presentation/dto/response/Fc001aDTO.java
- control/src/main/java/com/postco/control/service/ErrorMaterialQueryService.java
- control/src/main/java/com/postco/control/service/NextProcessQueryService.java
- control/src/main/java/com/postco/control/service/impl/ErrorMaterialQueryServiceImpl.java
- control/src/main/java/com/postco/control/service/impl/ProcessCounter.java
- 50
- refactoring/control/leeyc
- 기능적으로 변경된 부분은 없고, 기존에 Mock 데이터로 쓰던 방식에서 Redis로 데이터 받아서 처리하도록 수정
- 프론트와 API 테스트 완료 
- #50 
- 차공정 조회 부분은 나중에 수정해야할 수도 있을것 같아요! 우선 화면 얼른 찍어내고 변경하도록 할게요! 
- 
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @dudco0040 
- @yerimee82
> [FEAT/Refactoring/leeyc] 관제파트 리팩토링 

- control/src/main/java/com/postco/control/domain/repository/TargetMaterialRepository.java
- control/src/main/java/com/postco/control/presentation/ErrorMaterialController.java
- control/src/main/java/com/postco/control/presentation/TargetMaterialController.java
- control/src/main/java/com/postco/control/service/ErrorMaterialQueryService.java
- control/src/main/java/com/postco/control/service/ErrorPassService.java
- control/src/main/java/com/postco/control/service/impl/TargetMaterialQueryServiceImpl.java
- operation/src/main/java/com/postco/operation/domain/entity/Materials.java
- #59 
- feat/bm/hanriverkitty
- 에러재 comment API 작성 및 operation 에 remarks 컬럼 추가
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Feat/bm/hanriverkitty 모바일 API

- control/src/main/java/com/postco/control/domain/ErrorCriteriaMapper.java
- control/src/main/java/com/postco/control/presentation/ErrorMaterialController.java
- control/src/main/java/com/postco/control/presentation/ManagementController.java
- control/src/main/java/com/postco/control/service/ManagementService.java
- control/src/main/java/com/postco/control/service/impl/ExtractionFilterService.java
- #39 
- feat/bme001-v2/pinky
- 기준관리 api 리팩토링 및 controller service 추가, ErrorMaterialController RequsetMapping 변경
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Feat/bme001-v2/pinky 기준관리

- control/src/main/java/com/postco/control/domain/repository/TargetMaterialRepository.java
- control/src/main/java/com/postco/control/presentation/ErrorMaterialController.java
- control/src/main/java/com/postco/control/presentation/dto/TargetViewDTO.java
- control/src/main/java/com/postco/control/service/ErrorPassService.java
- control/src/main/java/com/postco/control/service/impl/ErrorMaterialQueryServiceImpl.java
- control/src/main/java/com/postco/control/service/impl/TargetMaterialQueryServiceImpl.java
- operation/src/main/java/com/postco/operation/domain/entity/Materials.java
- #59 
- feat/bm/hanriverkitty
- builder 에 remarks 추가하여, 에러재와 정상재 모두에서 remarks 확인가능
- 기존에 remarks 내용 못불러오는 bug 해결
- #67 
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Feat/bm/hanriverkitty 에러재 조회 수정

- schedule/src/main/java/com/postco/schedule/service/impl/SchedulePlanServiceImpl.java
- schedule/src/main/java/com/postco/schedule/service/impl/SchedulingServiceImplRefac.java
- 예시 : 18
- 작업 중인 브랜치를 알려주세요.
- 
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> HOTFIX: 스케쥴링 시퀀스 세팅 추가

- control/src/main/java/com/postco/control/presentation/MonitoringController.java
- control/src/main/java/com/postco/control/service/MonitoringService.java
- #75 
- feat/bc003/hanriverkitty
- 저장위치별로 코일갯수 나타내는 API 조회
- 
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Feat: 저장위치그래프 API 작성

- schedule/src/main/java/com/postco/schedule/presentation/ManagementController.java
- schedule/src/main/java/com/postco/schedule/presentation/SCHForm.java
- schedule/src/main/java/com/postco/schedule/presentation/ScheduleController.java
- schedule/src/main/java/com/postco/schedule/service/impl/ScheduleConfirmServiceImpl.java
- schedule/src/main/java/com/postco/schedule/service/impl/SchedulePlanServiceImpl.java
- #60 
- Fix/schedule/ash
- Swagger를 위한 API endpoint 변경 
- #60 
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Fix: API endpoint 변경 for swagger

- control/src/main/java/com/postco/control/domain/repository/TargetMaterialRepository.java
- control/src/main/java/com/postco/control/presentation/ControlController.java
- control/src/main/java/com/postco/control/presentation/DashBoardController.java
- control/src/main/java/com/postco/control/presentation/ErrorMaterialController.java
- control/src/main/java/com/postco/control/presentation/TargetMaterialController.java
- control/src/main/java/com/postco/control/presentation/dto/response/Fc004aDTO.java
- control/src/main/java/com/postco/control/service/DashBoardMaterialService.java
- 86
- feat/bc004a/add graph.
- 대시보드에 공정 별 롤단위 개수 조회 기능 추가 
- #86 
- 
- swagger 사용
어떤 변경 사항이 있나요?
- API 테스트
- 화면 연결 
리뷰어를 태그해주세요.
- @dudco0040 
- @yerimee82
> [FEAT/bc004a/leeyc] 대시보드 공정 별 롤단위 통계

- operation/src/main/java/com/postco/operation/domain/entity/WorkInstruction.java
- operation/src/main/java/com/postco/operation/domain/entity/WorkInstructionItem.java
- operation/src/main/java/com/postco/operation/domain/repository/CoilSupplyRepository.java
- operation/src/main/java/com/postco/operation/domain/repository/WorkInstructionRepository.java
- operation/src/main/java/com/postco/operation/presentation/WorkInstructionController.java
- operation/src/main/java/com/postco/operation/presentation/dto/WorkInstructionDTO.java
- operation/src/main/java/com/postco/operation/presentation/dto/WorkInstructionItemDTO.java
- operation/src/main/java/com/postco/operation/presentation/dto/WorkInstructionMapper.java
- operation/src/main/java/com/postco/operation/presentation/dto/websocket/ClientDTO.java
- operation/src/main/java/com/postco/operation/service/WorkInstructionService.java
- operation/src/main/java/com/postco/operation/service/impl/WorkInstructionServiceImpl.java
- schedule/src/main/java/com/postco/schedule/domain/SCHMaterial.java
- schedule/src/main/java/com/postco/schedule/service/impl/SchedulingServiceImpl.java
- #96
- feat/operation/ash
- 웹소켓전 전달할 DTO를 ClientDTO에 매핑해서 반환하는 API 개발
- #96
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Feat/operation/ash 웹소켓 전 ClientDTO를 통한 API 개발

- control/src/main/java/com/postco/control/config/WebSocketConfig.java
- control/src/main/java/com/postco/control/infra/kafka/WebSocketConsumer.java
- control/src/main/java/com/postco/control/infra/kafka/WebSocketReceiverService.java
- control/src/main/java/com/postco/control/presentation/dto/websocket/ControlClientDTO.java
- control/src/main/java/com/postco/control/presentation/dto/websocket/DashBoardClientDTO.java
- control/src/main/java/com/postco/control/presentation/dto/websocket/MaterialProgress.java
- control/src/main/java/com/postco/control/presentation/dto/websocket/WebSocketMessageType.java
- control/src/main/java/com/postco/control/service/WebsocketService.java
- core/src/main/java/com/postco/core/config/WebMvcConfig.java
- core/src/main/java/com/postco/core/kafka/producer/KafkaProducer.java
- operation/build.gradle
- operation/src/main/java/com/postco/operation/domain/repository/MaterialRepositoryCustom.java
- operation/src/main/java/com/postco/operation/domain/repository/WorkInstructionRepositoryCustom.java
- operation/src/main/java/com/postco/operation/domain/repository/impl/MaterialCustomImpl.java
- operation/src/main/java/com/postco/operation/domain/repository/impl/WorkInstructionCustomImpl.java
- operation/src/main/java/com/postco/operation/infra/kafka/NullKeySerializer.java
- operation/src/main/java/com/postco/operation/infra/kafka/WebsocketProducer.java
- operation/src/main/java/com/postco/operation/presentation/dto/websocket/ControlClientDTO.java
- operation/src/main/java/com/postco/operation/service/impl/work/ClientDashboardService.java
- 예시 : 18
- 작업 중인 브랜치를 알려주세요.
- 
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Feat/controlop/tony 웹소켓 대시보드

- core/src/main/java/com/postco/core/config/WebMvcConfig.java
- operation/src/main/java/com/postco/operation/domain/repository/WorkInstructionRepository.java
- operation/src/main/java/com/postco/operation/presentation/WorkInstructionController.java
- operation/src/main/java/com/postco/operation/service/WorkInstructionService.java
- operation/src/main/java/com/postco/operation/service/impl/SupplyQueueManager.java
- operation/src/main/java/com/postco/operation/service/impl/WorkInstructionServiceImpl.java
- operation/src/main/java/com/postco/operation/service/impl/work/CoilWorkCommandService.java
- operation/src/main/java/com/postco/operation/service/util/WorkSimulationUtil.java
- #104 
- feat/operationAPI/v2/hanriverkitty
- 웹 소켓 연결 후, 보급요구, 작업 시작시, 작업완료 시 웹소켓 송신
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Feat/operationAPI/v2/hanriverkitty 웹소켓 

- schedule/src/main/java/com/postco/schedule/service/impl/RedisServiceImpl.java
- schedule/src/main/java/com/postco/schedule/service/impl/RegisterServiceImpl.java
- schedule/src/main/java/com/postco/schedule/service/impl/SchedulingServiceImplRefac.java
hotfix/schedule/tony
- 
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Hotfix/schedule/tony 스케쥴링 에러 해결 및 대상재 중복 저장 해결

- core/src/main/java/com/postco/core/config/WebMvcConfig.java
- operation/src/main/java/com/postco/operation/presentation/dto/WorkInstructionMapper.java
- 
- Feat/hotfix/hanriverkitty
- WebMVCConfig 코드 중복 수정 및 작업지시문에 startTime 이 null 로 들어가도록 재설정
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Feat/hotfix/hanriverkitty WebMVCConfig 수정 및 작업지시문 시작시간 수정

- control/src/main/java/com/postco/control/presentation/MonitoringController.java
- operation/src/main/java/com/postco/operation/domain/entity/WorkScheduleSummary.java
- operation/src/main/java/com/postco/operation/domain/repository/WorkScheduleSummaryRepository.java
- operation/src/main/java/com/postco/operation/presentation/MonitoringController.java
- operation/src/main/java/com/postco/operation/presentation/dto/WorkScheduleSummaryDTO.java
- operation/src/main/java/com/postco/operation/service/MonitoringService.java
- operation/src/main/java/com/postco/operation/service/MoritoringService.java
- operation/src/main/java/com/postco/operation/service/impl/MonitoringServiceImpl.java
- 101
-  feat/fc003a select/leeyc
- 일일 진행현황 조회 기능 추가 
- 웹소켓 데이터를 전달 받기 전 초기값으로 사용하기 위한 API 구현 
- #101 
- 
- WORK_SCHEDULE_SUMMARY 테이블(모니터링)을 사용하는건 없는거 같아서 controller, service, repository 모두 별도로 만들었는데, 비슷한 기능이 있어서 합쳐야할 부분이 있으면 수정하도록 하겠습니다~ 
어떤 변경 사항이 있나요?
- 1CAL, 2CAL 중 DB에 값이 없을 경우, 0으로 세팅
- 나머지 공정은 mock 데이터 
리뷰어를 태그해주세요.
- @dudco0040 
- @yerimee82
> [FEAT/fc003a/leeyc] 일일 작업 진행현황 모니터링 초기값 조회 

- schedule/src/main/java/com/postco/schedule/domain/SCHMaterial.java
- schedule/src/main/java/com/postco/schedule/service/impl/RegisterServiceImpl.java
- 예시 : #109
- hotfix/schedule/tony
- 스케쥴 대상재 중복저장 해결
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> HOTFIX: 스케쥴 대상재 중복 저장 에러 해결

- operation/src/main/java/com/postco/operation/presentation/dto/WorkInstructionMapper.java
- operation/src/main/java/com/postco/operation/service/impl/WorkItemServiceImpl.java
- #105 
- feat/operationAPI/v2/hanriverkitty
- reject 시 웹소켓으로 다시 정보 전달
- WorkInstructionItem 에 매핑오류 부분 수정
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> feat/operationAPI/v2/hanriverkitty  reject시 웹소켓으로 정보 전송 및 workInstruction 매핑 수정

- control/src/main/java/com/postco/control/infra/kafka/WebSocketConsumer.java
- control/src/main/java/com/postco/control/presentation/dto/websocket/ControlClientDTO.java
- control/src/main/java/com/postco/control/presentation/dto/websocket/DashBoardClientDTO.java
- control/src/main/java/com/postco/control/presentation/dto/websocket/WebSocketMessageType.java
- control/src/main/java/com/postco/control/service/WebsocketService.java
- operation/src/main/java/com/postco/operation/domain/repository/MaterialRepositoryCustom.java
- operation/src/main/java/com/postco/operation/domain/repository/WorkInstructionRepositoryCustom.java
- operation/src/main/java/com/postco/operation/domain/repository/impl/MaterialCustomImpl.java
- operation/src/main/java/com/postco/operation/domain/repository/impl/WorkInstructionCustomImpl.java
- operation/src/main/java/com/postco/operation/infra/kafka/WebsocketProducer.java
- operation/src/main/java/com/postco/operation/presentation/MonitoringController.java
- operation/src/main/java/com/postco/operation/presentation/dto/AnalysisDashboardClientDTO.java
- operation/src/main/java/com/postco/operation/presentation/dto/websocket/ControlClientDTO.java
- operation/src/main/java/com/postco/operation/service/impl/work/ClientDashboardService.java
- operation/src/main/java/com/postco/operation/service/impl/work/CoilWorkCommandService.java
Issue Number
예시 : https://github.com/POSTCO2024/postcoil-backend/issues/102
branch
feat/controlop/tony
📋 개요
변경 사항
웹소켓 대시보드 필요 정보별로 topic 발행, 송수신 정상 확인
웹소켓 초기 값 세팅 api 완료
관련 이슈 또는 문서
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Feat/controlop/tony 관제 API, 웹소켓 완료

- operation/src/main/java/com/postco/operation/domain/entity/WorkInstructionItem.java
- operation/src/main/java/com/postco/operation/presentation/WorkController.java
- operation/src/main/java/com/postco/operation/presentation/dto/WorkInstructionItemDTO.java
- operation/src/main/java/com/postco/operation/presentation/dto/WorkInstructionMapper.java
- #87 
- feat/operationAPI/v2/hanriverkitty
- workInstructionItem 엔티티에 initialGoalThickness 추가
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> feat/operationAPI/v2/hanriverkitty : workInstruction에 initailGoalThickness 추가

- operation/src/main/java/com/postco/operation/domain/repository/WorkInstructionRepository.java
- operation/src/main/java/com/postco/operation/domain/repository/WorkItemRepository.java
- operation/src/main/java/com/postco/operation/presentation/WorkInstructionController.java
- operation/src/main/java/com/postco/operation/presentation/WorkInstructionItemController.java
- operation/src/main/java/com/postco/operation/presentation/dto/WorkInstructionDTO.java
- operation/src/main/java/com/postco/operation/presentation/dto/WorkInstructionItemDTO.java
- operation/src/main/java/com/postco/operation/presentation/dto/WorkInstructionItemMapper.java
- operation/src/main/java/com/postco/operation/presentation/dto/WorkInstructionMapper.java
- operation/src/main/java/com/postco/operation/service/WorkInstructionService.java
- operation/src/main/java/com/postco/operation/service/WorkItemService.java
- operation/src/main/java/com/postco/operation/service/impl/WorkInstructionServiceImpl.java
- operation/src/main/java/com/postco/operation/service/impl/WorkItemServiceImpl.java
- #118
- feat/3dapi/tony
- 시뮬레이션 작업지시서 및 작업지시서에 맞는 아이템 불러오는 api 추가
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Feat/3dapi/tony 3d 시뮬레이션에 필요한 api 생성

- database/schedule/schedule_data_inserts.sql
- schedule/src/main/java/com/postco/schedule/presentation/ScheduleController.java
- schedule/src/main/java/com/postco/schedule/service/impl/SchedulePlanServiceImpl.java
- schedule/src/main/java/com/postco/schedule/service/impl/SchedulingServiceImplRefac.java
- #121
- refactor/schedule/ash
- 스케줄링 제약조건 리팩토링
- DB 수정
- #121 
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Refactor: Refactor/schedule/ash

- control/src/main/java/com/postco/control/domain/repository/TargetMaterialRepository.java
- control/src/main/java/com/postco/control/presentation/DashBoardController.java
- control/src/main/java/com/postco/control/service/DashBoardMaterialService.java
- control/src/main/java/com/postco/control/service/WebsocketService.java
- 119
- refactoring/dashboard-v1/leeyc
- 롤 단위 API 수정
- 웹소켓 topic 주소 변경
- #119 
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @dudco0040 
- @yerimee82
> [FEAT/bc004a/leeyc] 작업대상재 대시보드 API 리팩토링

- core/src/main/java/com/postco/core/config/WebMvcConfig.java
- schedule/src/main/java/com/postco/schedule/service/impl/SchedulePlanServiceImpl.java
- 
- fix/schedule-mapping/ash
- 재료를 변경할 때 MaterialId를 받지 않아 시퀀스 변경 에러 수정
- #63 
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Fix: materialId, targetId 받지않는 에러 수정

- control/src/main/java/com/postco/control/service/impl/TargetMaterialQueryServiceImpl.java
- 
- hotfix/hanriverkitty
- IsError 가 N인 코일들만 필터링
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> hotfix/hanriverkitty Fix: 정상재 조회함수 수정

- control/src/main/java/com/postco/control/presentation/TargetMaterialController.java
- control/src/main/java/com/postco/control/presentation/dto/response/Fc001aDTO.java
- control/src/main/java/com/postco/control/service/NextProcessQueryService.java
- control/src/main/java/com/postco/control/service/impl/ProcessCounter.java
- 131
- Refactoring/bc001 table/leeyc
- 공정 별 작업대상재 차공정 표 백앤드 수정
- 화면 연결 완료 
- #131 
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @dudco0040 
- @yerimee82
> [Refactoring/bc001/leeyc] 공정 별 작업대상재 차공정 표 백앤드 수정

- operation/src/main/java/com/postco/operation/presentation/dto/WorkInstructionItemDTO.java
- operation/src/main/java/com/postco/operation/presentation/dto/WorkInstructionItemMapper.java
feat/operation/tony
- 
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> FEAT: 시뮬레이션 item 컬럼 추가

- control/src/main/java/com/postco/control/service/TargetMaterialService.java
- control/src/main/java/com/postco/control/service/impl/RollUnitService.java
- control/src/main/java/com/postco/control/service/impl/TargetMaterialServiceImpl.java
- control/src/main/resources/application.yml
- operation/src/main/java/com/postco/operation/domain/entity/Materials.java
- operation/src/main/resources/application.yml
- schedule/src/main/java/com/postco/schedule/domain/repository/SCHMaterialRepository.java
- schedule/src/main/java/com/postco/schedule/presentation/ScheduleController.java
- schedule/src/main/java/com/postco/schedule/service/impl/SchedulePlanServiceImpl.java
- schedule/src/main/resources/application.yml
- 
- 작업 중인 브랜치를 알려주세요.
- 
-
-
-
어떤 변경 사항이 있나요?
리뷰어를 태그해주세요.
- @yerimee82
> Feature/load test/yerimee
